server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: fillsa_api

  datasource:
    url: jdbc:mysql://localhost:3306/fillsa_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 2MB

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
  access-token-validity: 10800000   # 3시간
  refresh-token-validity: 7776000000   # 90일

logging:
  level:
    root: INFO
    store.fillsa.fillsa_api: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.orm.jdbc.bind: trace

  file:
    name: logs/fillsa_api.log

oauth:
  kakao:
    client-id:
    client-secret:
    redirect-uri:
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
  google:
    client-id:
    client-secret:
    redirect-uri:
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static:
    s3:
      bucket:

fillsa:
  security:
    actuator-path:
    swagger-path:
  ko-author-url: https://ko.wikipedia.org/wiki/
  en-author-url: https://en.wikipedia.org/wiki/
  withdraw-url:

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    path:
    url:
  api-docs:
    path:
  enable-spring-security: true
  writer-with-order-by-keys: false

swagger:
  server-url: http://localhost:8080