spring:
  application:
    name: fillsa_api

  datasource:
    url: jdbc:mysql://localhost:3306/fillsa_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 2MB

jwt:
  secret:
  access-token-validity: 900000   # 15분
  refresh-token-validity: 604800000   # 7일

oauth:
  kakao:
    client-id:
    client-secret:
    redirect-uri:
    token-uri:
    user-info-uri:
  google:
    client-id:
    client-secret:
    redirect-uri:
    token-uri:
    user-info-uri: